# Generated by Django 4.0.3 on 2022-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Psychology', 'Psychology'), ('Philosophy', 'Philosophy'), ('Poetry', 'Poetry'), ('History', 'History'), ('Fiction', 'Fiction'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
