# Generated by Django 4.0.3 on 2022-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_author_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
